[[Tk]]
arch = "aarch64"
git-tree-sha1 = "11e9697ab805a2a6a0560cf8e78f0b102b32e7c0"
os = "macos"

    [[Tk.download]]
    sha256 = "8a4abea337d2cb30240914ff53e52c22f9deed227ed5a3b8c18b5da08402c73c"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.aarch64-apple-darwin.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "60e4da840a5ebe42ab4b953743b56a7dd2121bc3"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "4939db63f221026a621d039655dfd5df5ffd3246e9e2dd552f34952199151e63"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.aarch64-linux-gnu.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "6a715264f198700c8088047bb2c9ee49063ef186"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "e49e367686d1867336d865bb76af736f11ef343236390fbe85474641918012ed"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.aarch64-linux-musl.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "52f6481bf208a1f6dbb9657b9a4815bac1ed72b1"
os = "freebsd"

    [[Tk.download]]
    sha256 = "579a05a662f1dac73580f36e9f9f6ede51ac193bdc1447abea1404c0220b9e5b"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.aarch64-unknown-freebsd.tar.gz"
[[Tk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2489e58d91fdcfb04b5f2ac7d5363f22f5686f8e"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "0b9afc8c548846b8a4a43e19311466ff169737c0cec3ec0a96e828124dbab9d5"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.armv6l-linux-gnueabihf.tar.gz"
[[Tk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7138f65d4606378b69a75d1884bc1b0b6c9b104"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "cf0bda7a2eeea8735364a828bd0bb79e1b39fa94ba06eb668ae41fa658d448d6"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.armv6l-linux-musleabihf.tar.gz"
[[Tk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "485717579b25a360e0eaf16eb47823aec85f6d1b"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "b5061133733e7700454f2421a83724ddc660e4969b94a496b4902f31d7a253b6"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.armv7l-linux-gnueabihf.tar.gz"
[[Tk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "392b1c8f9a604872e03206a1e932ca0462e21d7e"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "6d604e85c6227be3ab7eda4d38cc077adad4de2e2d687cbdd5b818d2020ea2c6"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.armv7l-linux-musleabihf.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "3eb3ff2663d1aa8bf3894973933601cf83481d82"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "367606b8dc7ff714bf91003244e4d6b8e03cba18e7983c0cf598597cb64c6f77"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.i686-linux-gnu.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "7ab488bb11a49e2fed9fd7f16e5ab132e2637c70"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "4c509d37cc4e361b314b8bf1e8545a12b930334b9304bff942ba2eebfc8d8a7c"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.i686-linux-musl.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "5b382745da8005862b2d302fb7eba372177a3d87"
os = "windows"

    [[Tk.download]]
    sha256 = "51391c7f69cd7851beed98f739e509f8ae7d610b609c0a276c20156f30e620ba"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.i686-w64-mingw32.tar.gz"
[[Tk]]
arch = "powerpc64le"
git-tree-sha1 = "9673ac36d4adcdd1f2bbe5b0ec125fe300587d70"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "77b202cffaf6e83bd127bf7683dc80c36ecfe81c0195f152297d0e37f38b1a27"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.powerpc64le-linux-gnu.tar.gz"
[[Tk]]
arch = "riscv64"
git-tree-sha1 = "e2db7153c221c2f4d21a150c003d3dba77425a26"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "fc5f8306a43c67c3efd50f035868be297418ce423b5aa2835f3d6f517a61d5db"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.riscv64-linux-gnu.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "15a629d6cb3fd0767cbf506f3579257b688a8251"
os = "macos"

    [[Tk.download]]
    sha256 = "ce2c560871ec563185eb3e8ac7d92a9f2600df5e4b0788f2cfaaecc02f9f234a"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.x86_64-apple-darwin.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "0d203df0af4d74db5be2470ee58e35ec094353e4"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "8d9926a50bee2d7c982bc4d6706c1868249212076a4105e31150547721b36b85"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.x86_64-linux-gnu.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "dd52ba6714482992c5c7bc0f8ee29affcbc77c61"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "3c0a615d2ff3b3eaef5ea473a969ce6a7004bfcc8f422b2a8bc64dc4e184778b"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.x86_64-linux-musl.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "2c6f5e3ef7b29dbd8f31b05f4118e38f233e6ef8"
os = "freebsd"

    [[Tk.download]]
    sha256 = "4d3d070391c05a0beec593aa47f82affb4224cec0fd22524765dfa5c4bbd827d"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.x86_64-unknown-freebsd.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "d54b0aa2fdc9f5590d588aa37caf7b1c10de6d4b"
os = "windows"

    [[Tk.download]]
    sha256 = "1a7cbfed0911ed737d79bf08103610a92164fa727560e28954533ac100fd802e"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+2/Tk.v9.0.3.x86_64-w64-mingw32.tar.gz"
