[[Tk]]
arch = "aarch64"
git-tree-sha1 = "941b9b4db2e3167bfe6b111f5ce8498533cba9fc"
os = "macos"

    [[Tk.download]]
    sha256 = "0390bdb7a0243807605b7f97d600e7aadcfcb50898b8bca2498aaed7197384b8"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.aarch64-apple-darwin.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "603e11a955e4a3660557dc5a6bfcdb02bda86959"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "8dc68c772fc70a5d19568a3f243e480c8090f55b0bc714b5ec6c886ffbbb3e06"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.aarch64-linux-gnu.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "b13d93099c63923dddf1f507078466be39090dab"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "3b760e991052e7e987fba93a8d9625fb5d125d4a9253e9f7e027b980f28c2336"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.aarch64-linux-musl.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "52f6481bf208a1f6dbb9657b9a4815bac1ed72b1"
os = "freebsd"

    [[Tk.download]]
    sha256 = "579a05a662f1dac73580f36e9f9f6ede51ac193bdc1447abea1404c0220b9e5b"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.aarch64-unknown-freebsd.tar.gz"
[[Tk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db3f6094d084be1e2012659a400049a8065511fb"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "68a7753d0aff59f5d04a76b258fb40758b3f009a47d2d43d416f271b7c87b541"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.armv6l-linux-gnueabihf.tar.gz"
[[Tk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb57f348c18ce6569ae6b51bfa1d6e7ef163871a"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "cef8a3032944ab7e4bef22d8209b558195e5697c72ab68b32cecc5eb1a23fa41"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.armv6l-linux-musleabihf.tar.gz"
[[Tk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1de2101c62a30000f9e5fcbbe8d7918909404eae"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "35ecb69dd25c87bd279b571f5be1a414f0eb0e1d6f187e2824716ae934216d71"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.armv7l-linux-gnueabihf.tar.gz"
[[Tk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b309de4bc5b70b458d9d424e960e4d93a07ec70f"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "db49346f9b108b89eb82686a2322787953ee989c0841042b31a4f38b3f8e4581"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.armv7l-linux-musleabihf.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "e659ded333498f67459ec8c3df4b14e656e22357"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "60c6a6c5dd7c16ad17c90c6e71ac7c108657f7f52b055abdf493f705b49a5e66"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.i686-linux-gnu.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "20c9a65cbf95ceeb0cd4eb235cc5f18ffab33ac8"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "0d9b36986d9870a94522236cb60bf6438cacf453c85225d837e1bc130006acd1"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.i686-linux-musl.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "7275be8dc60cdb43afdc8cc2f7c7733031d7440d"
os = "windows"

    [[Tk.download]]
    sha256 = "093f22b8899686c19deb145100a2cc43417630c3fdc685138459bf22852ebf79"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.i686-w64-mingw32.tar.gz"
[[Tk]]
arch = "powerpc64le"
git-tree-sha1 = "a875a2e4c03939789c3509bd8a9a418c7881e6e3"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "7e5bfeb33314a6efc127cb37c217c263fe4cc927ed6537eff86798696c1cc620"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.powerpc64le-linux-gnu.tar.gz"
[[Tk]]
arch = "riscv64"
git-tree-sha1 = "e2db7153c221c2f4d21a150c003d3dba77425a26"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "fc5f8306a43c67c3efd50f035868be297418ce423b5aa2835f3d6f517a61d5db"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.riscv64-linux-gnu.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "b7ce548a805acf296cc158f87d702ef072b90934"
os = "macos"

    [[Tk.download]]
    sha256 = "4c767c5c5bc7221a7faa23dd8ba1da31a554f9f871a17fae255aa6d95d2df960"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.x86_64-apple-darwin.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "7590d4e4cb5ab06147b52a87a3189476b8ca7b40"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "d6d854c354736139558e1aa5871d0c252cc611ffbbb24e56f5b08ebb8d9dc040"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.x86_64-linux-gnu.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "24a6097196642990473a632ca5de8951917beab3"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "90f47af19be2a16c92ccc0e457d8d444a605eac507f6891b7baed94548c62895"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.x86_64-linux-musl.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "2c6f5e3ef7b29dbd8f31b05f4118e38f233e6ef8"
os = "freebsd"

    [[Tk.download]]
    sha256 = "4d3d070391c05a0beec593aa47f82affb4224cec0fd22524765dfa5c4bbd827d"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.x86_64-unknown-freebsd.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "36e488634f2f2694400acb39db294a84686ca77d"
os = "windows"

    [[Tk.download]]
    sha256 = "6eaf36e43efd7a9311e5fb8241721421cc846b846742257c84f2807159d6c176"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+1/Tk.v9.0.3.x86_64-w64-mingw32.tar.gz"
