[[Tk]]
arch = "aarch64"
git-tree-sha1 = "941b9b4db2e3167bfe6b111f5ce8498533cba9fc"
os = "macos"

    [[Tk.download]]
    sha256 = "0390bdb7a0243807605b7f97d600e7aadcfcb50898b8bca2498aaed7197384b8"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.aarch64-apple-darwin.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "82da44957087e78ee4e98eba2fd28b1931c59d36"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "6bed06142c10c711940a3a70d22601ac9c6eebff37f3b6c96b5fa6de0e8dc60c"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.aarch64-linux-gnu.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "4c0e5be7e7a7a1b08416c43e5aa7770065fb1ef3"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "32951007a0c798e3438343c0e329fdbea5ad524b6f5649bfde147bed6df93014"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.aarch64-linux-musl.tar.gz"
[[Tk]]
arch = "aarch64"
git-tree-sha1 = "4addd19c2de9405ec806ff779408c3ccf7e0525e"
os = "freebsd"

    [[Tk.download]]
    sha256 = "09cbb62e85bea5f964676b1f0f80fb7d9d80646ed912aeb9784c8e55294aa326"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.aarch64-unknown-freebsd.tar.gz"
[[Tk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6921711846796fdab033171192514116cbc2c706"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "e2b57a66c813ea452d831024349016ffbb08dc15e2a948a7d123a6b43b48b4e5"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.armv6l-linux-gnueabihf.tar.gz"
[[Tk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "607e9731bde97c751659f4674c25007c47c36a7b"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "60c950b1dc0eeba89373b76cc8676cdc3f1838eaca913f7f92b20ddcd001b0db"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.armv6l-linux-musleabihf.tar.gz"
[[Tk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8b2d94e9b567c00c3d3a71db8c50d53466356da1"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "d4c96f1ff717f9bc56595d205417daa6e776350789bd19a5f429f52327de8018"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.armv7l-linux-gnueabihf.tar.gz"
[[Tk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd9bc5964c5e150164dc5a520a80b46195f1126e"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "36fa3697e61b7e7881f6fbbe0722e55e32019255606c76adcb61a5e0b8fccc4e"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.armv7l-linux-musleabihf.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "05c14bce795e8cdcc2233396ccee0959d043dc89"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "d0953bb14dcc20d9f0011e345223989e34858cbcb77ec58e8436b9274be4f1e3"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.i686-linux-gnu.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "7cf68c22438d34a8b69655095f58e695fbb79748"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "22884c1831fd0cb967c8db7ed879b989298711150bb6632c6bc3b39bb9edd5fb"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.i686-linux-musl.tar.gz"
[[Tk]]
arch = "i686"
git-tree-sha1 = "00571a9c0c8643fcff2c70d7edf617c17f744471"
os = "windows"

    [[Tk.download]]
    sha256 = "b9be55c52f0637cad1f4e6c2a159bd7d11bddbefce3d4907f8d08ac2bcb357f7"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.i686-w64-mingw32.tar.gz"
[[Tk]]
arch = "powerpc64le"
git-tree-sha1 = "9b971e5441d7e9fd2124f7fa4489b4742523a16c"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "7ec09e2a060bafbeb5a2ae2a0a607d1c771b5bcd25c158b3974c5ab2e4319788"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.powerpc64le-linux-gnu.tar.gz"
[[Tk]]
arch = "riscv64"
git-tree-sha1 = "443ac6fefc4f3149b874d6efedb261fa9945a33a"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "cac776ea0dec80338667a07716afcfac5959122414c606dfd040a2dd33059aca"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.riscv64-linux-gnu.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "b7ce548a805acf296cc158f87d702ef072b90934"
os = "macos"

    [[Tk.download]]
    sha256 = "4c767c5c5bc7221a7faa23dd8ba1da31a554f9f871a17fae255aa6d95d2df960"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.x86_64-apple-darwin.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "1c9807cfee08f5f4a9827506958c535195a3abd4"
libc = "glibc"
os = "linux"

    [[Tk.download]]
    sha256 = "75b7b37e0c7b1869cd5be2b901670b1e498d62f84c643b7e2bc6020b0190d1b2"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.x86_64-linux-gnu.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "1961307bfc684d8e70fcaf831b6a318399aaddcb"
libc = "musl"
os = "linux"

    [[Tk.download]]
    sha256 = "92839fbfe05c07e00997963bbb08086f508b29cbce29283f4ff97f3780af2cc0"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.x86_64-linux-musl.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "2d0bab6c6381033ba4694b52a7931aff5660c5c4"
os = "freebsd"

    [[Tk.download]]
    sha256 = "f6abb4159e67a5b5e1922c6b3ea16591b440f73f5f369f291ee2f9c3772c3814"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.x86_64-unknown-freebsd.tar.gz"
[[Tk]]
arch = "x86_64"
git-tree-sha1 = "f1ed5b93b34a9049c2b5efb9f84d435c57cf5e8f"
os = "windows"

    [[Tk.download]]
    sha256 = "30fbd8fe37f6ea4d8393463417f053cc19882174f94b09f800b0f137c27ff3e0"
    url = "https://github.com/JuliaBinaryWrappers/Tk_jll.jl/releases/download/Tk-v9.0.3+0/Tk.v9.0.3.x86_64-w64-mingw32.tar.gz"
